Catalogo/urls.py
from django.urls import path
from Catalogo import views

urlpatterns = [
    path('', views.index, name='index'),
    path('cervezas/', views.CervezaListView.as_view(), name='cervezas'),
    path('cerveza/<pk>', views.CervezaDetailView.as_view(), name='cerveza'),
    path('cerveza/<int:pk>/editar/', views.CervezaUpdateView.as_view(), name='cerveza_update'),
    path('cerveza/<int:pk>/eliminar/', views.borrar_cerveza, name='cerveza_delete'),
    path('cerveza/new/', views.CervezaCreateView.as_view(), name='cerveza_new'),
    path('servicios/<cerveza_id>', views.ServicioListView.as_view(), name='servicios'),
    path('servicio/<int:pk>/', views.ServicioDetailView.as_view(), name='servicio'),
    path('venta/<int:cerveza_id>/servicio/<int:servicio_id>/', views.realizar_venta, name='venta'),
    path('NuestrosServicios/', views.ServicioEstaticoListView.as_view(), name='servicioEstatico_List'),
    path('NuestrosServicios/nuevo/', views.ServicioCreateView.as_view(), name='servicio_crear'),
    path('NuestrosServicios/<int:pk>/editar/', views.ServicioUpdateView.as_view(), name='servicio_editar'),
    path('NuestrosServicios/<int:pk>/eliminar/', views.ServicioDeleteView.as_view(), name='servicio_eliminar'),
    path('cerveza/<int:cerveza_id>/barriles/', views.editar_stock_barriles, name='editar_stock_barriles'),
    path('barril/<int:barril_id>/editar/', views.editar_barril, name='editar_stock_barril'),
    path('barril/<int:barril_id>/eliminar/', views.eliminar_barril, name='eliminar_barril'),
    path('choperas/', views.editar_stock_choperas, name='editar_stock_choperas'),
    path('chopera/<int:chopera_id>/editar/', views.editar_chopera, name='editar_chopera'),
    path('chopera/<int:chopera_id>/eliminar/', views.eliminar_chopera, name='eliminar_chopera'),
    path('estadisticas/ventas/', views.grafico_ventas_cervezas, name='grafico_ventas'),
    
    path('findUs/', views.generic.TemplateView.as_view(template_name='findUs.html'), name='findUs'),
    path('contacto/', views.generic.TemplateView.as_view(template_name='contacto.html'), name='contacto'),
]

Catalogo_Beer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalogo/', include('Catalogo.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/catalogo/', permanent=False)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Catalogo/forms.py
from django import forms
from Catalogo.models import Cerveza, TipoServicio, Chopera, Barril, Servicio
from django.utils import timezone
from datetime import timedelta

class CervezaForm(forms.ModelForm):
    class Meta:
        model = Cerveza
        fields = ['nombre', 'descripcion', 'estilo', 'porcentaje_alcohol', 'ibu']

PROVINCIAS = [
    ('Salta', 'Salta'),
]


class VentaForm(forms.Form):
    barril = forms.ModelChoiceField(queryset=Barril.objects.none(), label="Formato (Litros)")
    cantidad = forms.IntegerField(min_value=1, label="Cantidad")
    fecha_alquiler = forms.DateField(
        label="Fecha de alquiler",
        widget=forms.DateInput(attrs={'type': 'date'}),  # cambiamos a DateInput para usar min y max
        initial=timezone.now().date()
    )
    provincia = forms.ChoiceField(choices=PROVINCIAS, label="Provincia")
    localidad = forms.CharField(max_length=50, label="Localidad")
    direccion = forms.CharField(widget=forms.Textarea, label="Dirección exacta")

    def __init__(self, cerveza, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['barril'].queryset = Barril.objects.filter(cerveza=cerveza, stock__gt=0)

        today = timezone.now().date()
        max_day = today + timedelta(days=60)

        # Limitamos el input para que solo permita fechas dentro del rango
        self.fields['fecha_alquiler'].widget.attrs['min'] = today.isoformat()
        self.fields['fecha_alquiler'].widget.attrs['max'] = max_day.isoformat()

    def clean_fecha_alquiler(self):
        fecha = self.cleaned_data['fecha_alquiler']
        hoy = timezone.now().date()
        limite = hoy + timedelta(days=60)
        if fecha < hoy:
            raise forms.ValidationError("No podés seleccionar una fecha anterior a hoy.")
        if fecha > limite:
            raise forms.ValidationError("No podés seleccionar una fecha con más de 60 días de anticipación.")
        return fecha
    def clean(self):
        cleaned_data = super().clean()
        provincia = cleaned_data.get("provincia")
        localidad = cleaned_data.get("localidad")
        direccion = cleaned_data.get("direccion")

        ubicacion = f"{direccion}, {localidad}, {provincia}"
        cleaned_data["ubicacion_entrega"] = ubicacion  # esta será pasada a la vista

        return cleaned_data
    
class ServicioForm(forms.ModelForm):
    class Meta:
        model = Servicio
        fields = ['nombre', 'descripcion', 'tipo', 'precio', 'foto']
        widgets = {
            'descripcion': forms.Textarea(attrs={'rows': 4}),
        }

class BarrilForm(forms.ModelForm):
    class Meta:
        model = Barril
        fields = ['litros', 'stock']  

class ChoperaForm(forms.ModelForm):
    class Meta:
        model = Chopera
        fields = ['numero', 'disponible']

Catalogo/views.py
from django.shortcuts import render

# Create your views here.
from django.views import generic
from .models import Cerveza, Servicio, Barril, DetallePedido, Pedido
import calendar
from datetime import date, timedelta
#gepeto
from django.views.generic import FormView, DeleteView
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from .models import Cerveza, Pedido, DetallePedido, Servicio, Chopera
from .forms import VentaForm, ServicioForm, BarrilForm, ChoperaForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from django.contrib import messages
#graficos
import pandas as pd
import matplotlib.pyplot as plt
from io import BytesIO
import base64





def index(request):
    return render(request, 'index.html')


class CervezaListView(generic.ListView):
    model = Cerveza
    template_name = 'cerveza_list.html'
    context_object_name = 'cervezas'

class CervezaDetailView(generic.DetailView):
    model = Cerveza
    template_name = 'cerveza_detail.html'
    context_object_name = 'cerveza'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['barriles'] = self.object.barriles.all()
        return context

class CervezaCreateView(LoginRequiredMixin,generic.CreateView):
    model = Cerveza
    fields = ['nombre', 'descripcion', 'estilo', 'porcentaje_alcohol', 'ibu', 'precio_litro', 'foto']

    template_name = 'cerveza_new.html'
    success_url = '/catalogo/cervezas/' 

class CervezaUpdateView(LoginRequiredMixin,generic.UpdateView):
    model = Cerveza
    fields = ['nombre', 'descripcion', 'estilo', 'porcentaje_alcohol', 'ibu', 'foto']
    template_name = 'cerveza_form.html'
    success_url = '/catalogo/cervezas/'


@login_required
def borrar_cerveza(request, pk):
    cerveza = get_object_or_404(Cerveza, pk=pk)

    if request.method == 'POST':
        cerveza.delete()
        return redirect('cervezas') 
    
    return redirect('cervezas')



class ServicioListView(generic.ListView):
    model = Servicio
    template_name = 'servicio_list.html'
    context_object_name = 'servicios'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cerveza_id = self.kwargs.get('cerveza_id')
        cerveza = get_object_or_404(Cerveza, pk=cerveza_id)
        context['cerveza'] = cerveza
        context['barriles'] = cerveza.barriles.all()  
        return context

class ServicioDetailView(generic.DetailView):
    model = Cerveza
    template_name = 'cerveza_detail.html'
    context_object_name = 'servicio'

#vista que recive 2 parametros desde la url
def generar_calendario_html(cerveza_id, servicio_id):
    hoy = date.today()
    año = hoy.year
    mes = hoy.month

    cerveza = get_object_or_404(Cerveza, id=cerveza_id)
    servicio = get_object_or_404(Servicio, id=servicio_id)

    print("VENTAAA")
    dias_ocupados = Pedido.objects.filter(
        servicio=servicio,
        fecha_alquiler__month=mes,
        fecha_alquiler__year=año
    ).values_list('fecha_alquiler', flat=True)

    class CalendarioDisponible(calendar.HTMLCalendar):
        def formatday(self, day, weekday):
            if day == 0:
                return '<td></td>'  # Día vacío

            fecha_actual = date(año, mes, day)
            if fecha_actual in dias_ocupados:
                return f'<td class="text-muted bg-light">{day}</td>'
            return f'<td class="text-success font-weight-bold">{day}</td>'

    cal = CalendarioDisponible()
    return cal.formatmonth(año, mes)

# en tu vista
def realizar_venta(request, cerveza_id, servicio_id):
    cerveza = get_object_or_404(Cerveza, id=cerveza_id)
    servicio = get_object_or_404(Servicio, id=servicio_id)

    calendario_html = generar_calendario_html(cerveza_id, servicio_id)

    if request.method == 'POST':
        print("POSTT")
        form = VentaForm(cerveza, request.POST)
        if form.is_valid():
            print("no es validoooooooooo")
            barril = form.cleaned_data['barril']
            cantidad = form.cleaned_data['cantidad']
            ubicacion_entrega=form.cleaned_data['ubicacion_entrega']
            provincia = request.POST.get('provincia')
            localidad = request.POST.get('localidad')
            direccion = request.POST.get('direccion')
            ubicacion = f"{direccion}, {localidad}, {provincia}"

            if cantidad > barril.stock:
                form.add_error('cantidad', 'Cantidad mayor al stock disponible')
            else:
                if servicio.tipo.nombre == 'Chopera':
                    print("CHOPERAAA")
                    choperas_disponibles = Chopera.objects.filter(disponible=True)
                    cantidad_choperas = choperas_disponibles.count()

                    if cantidad_choperas == 0:
                        form.add_error(None, "No hay choperas disponibles para este servicio.")
                    elif cantidad > cantidad_choperas:
                        form.add_error('cantidad', f'Solo hay {cantidad_choperas} choperas disponibles.')
                    else:
                        # crear pedido, asignar choperas, etc.
                        pedido = Pedido.objects.create(servicio=servicio)
                        DetallePedido.objects.create(
                            pedido=pedido,
                            barril=barril,
                            cantidad=cantidad,
                            subtotal=barril.calcular_precio() * cantidad
                        )
                        pedido.actualizar_total()

                        # Marcar las choperas asignadas como ocupadas (las primeras 'cantidad')
                        choperas_asignadas = choperas_disponibles[:cantidad]
                        for chopera in choperas_asignadas:
                            chopera.disponible = False
                            chopera.save()
                        
                        messages.success(request, "¡Venta realizada con éxito!")
                        return redirect('cervezas')
                else:
                    # crear pedido, asignar choperas, etc.
                    pedido = Pedido.objects.create(servicio=servicio)
                    DetallePedido.objects.create(
                        pedido=pedido,
                        barril=barril,
                        cantidad=cantidad,
                        subtotal=barril.calcular_precio() * cantidad
                    )
                    pedido.actualizar_total()
                    messages.success(request, "¡Venta realizada con éxito!")
                    return redirect('cervezas')
                    

                pedido = Pedido.objects.create(
                    servicio=servicio,
                    fecha_alquiler=form.cleaned_data['fecha_alquiler'],
                    ubicacion_entrega=ubicacion 
                )
                DetallePedido.objects.create(
                    pedido=pedido,
                    barril=barril,
                    cantidad=cantidad,
                    subtotal=barril.calcular_precio() * cantidad
                )
                pedido.actualizar_total()
                return redirect('cervezas')
    else:
        form = VentaForm(cerveza)

    return render(request, 'venta_form.html', {
        'form': form,
        'cerveza': cerveza,
        'servicio': servicio,
        'calendario_html': calendario_html
    })


    
class ServicioEstaticoListView(generic.ListView):
    model = Servicio
    template_name = 'servicioEstatico_List.html'  # nombre del archivo HTML
    context_object_name = 'servicios'     # variable en el template

class ServicioCreateView(LoginRequiredMixin,generic.CreateView):
    model = Servicio
    form_class = ServicioForm
    template_name = 'servicio_form.html'
    success_url = reverse_lazy('servicioEstatico_List')   # redirige a la lista
    login_url = '/accounts/login/'


class ServicioUpdateView(LoginRequiredMixin,generic.UpdateView):
    model = Servicio
    form_class = ServicioForm
    template_name = 'servicio_form.html'
    success_url = reverse_lazy('servicioEstatico_List')

class ServicioDeleteView(LoginRequiredMixin,DeleteView):
    model = Servicio
    template_name = 'servicio_confirm_delete.html'
    success_url = reverse_lazy('servicioEstatico_List')

#para control de barriles y stock
def editar_stock_barriles(request, cerveza_id):
    cerveza = get_object_or_404(Cerveza, pk=cerveza_id)
    barriles = Barril.objects.filter(cerveza=cerveza)

    if request.method == "POST":
        form = BarrilForm(request.POST)
        if form.is_valid():
            nuevo_barril = form.save(commit=False)
            nuevo_barril.cerveza = cerveza

            # busca si ya existe un barril con la misma cerveza y litros
            barril_existente = Barril.objects.filter(
                cerveza=cerveza,
                litros=nuevo_barril.litros 
            ).first()

            if barril_existente:
                #sumar el stock del nuevo barril al existente
                barril_existente.stock += nuevo_barril.stock
                barril_existente.save()
            else:
                nuevo_barril.save()

            return redirect('editar_stock_barriles', cerveza_id=cerveza.id)
    else:
        form = BarrilForm()

    return render(request, 'editar_stock_barriles.html', {
        'cerveza': cerveza,
        'barriles': barriles,
        'form': form
    })



def editar_barril(request, barril_id):
    barril = get_object_or_404(Barril, pk=barril_id)

    if request.method == 'POST':
        form = BarrilForm(request.POST, instance=barril)
        if form.is_valid():
            form.save()
            return redirect('editar_stock_barriles', cerveza_id=barril.cerveza.id)
    else:
        form = BarrilForm(instance=barril)

    return render(request, 'editar_barril.html', {'form': form, 'barril': barril})

Catalogo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>O'dowd: Cerveza</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js" integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf" crossorigin="anonymous"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    
 <!-- Add additional CSS in static file -->
      {% load static %}

        <!-- CSS FILES -->  
    <link rel="preconnect" href="https://fonts.googleapis.com">
        
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Unbounded:wght@300;500&display=swap" rel="stylesheet">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/odowStyle.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">

</head>

    <body>
        <div class="container-fluid">
            <div class="row">
                <button class="navbar-toggler d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <nav id="sidebarMenu" class="col-md-4 col-lg-3 d-md-block sidebar collapse p-0">

                    <div class="position-sticky sidebar-sticky d-flex flex-column justify-content-center align-items-center">
                        <a class="navbar-brand" href="http://127.0.0.1:8000/catalogo/">
                            <img src="{% static 'imgs/logoOdou-removebg-preview.png' %}" class="logo-image img-fluid" align="">
                        </a>
                        {% block sidebar %}

                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link click-scroll" href="{% url 'cervezas' %}">Products</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link click-scroll" href="#section_2">Our Story</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link click-scroll" href="{% url 'servicioEstatico_List' %}">Services</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link click-scroll" href="{% url 'findUs' %}">Find Us</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link click-scroll" href="{% url 'contacto' %}">Contact</a>
                            </li>
                        </ul>
                        {% endblock %}
                        {% if user.is_authenticated %}
                        <br>
                        <p>Sesión iniciada como {{ user.username }} | </p>
                        <form method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-link">Cerrar sesión</button>
                        </form>
                        {% endif %}
                    </div>
                </nav>
                <div class="col-md-8 ms-sm-auto col-lg-9 p-0">
                    {% block content %}{% endblock %}
                </div>
            </div>
            
        </div>
    </div>
    <!-- JAVASCRIPT FILES -->
    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/click-scroll.js"></script>
    <script src="js/custom.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>

Catalogo/templates/cerveza_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
  <div class="card text-white bg-dark">
    <div class="card-body">
      <h1 class="card-title">{{ cerveza.nombre }}</h1>

      <img src="{{ cerveza.foto.url }}" alt="{{ cerveza.nombre }}" class="img-fluid mb-3" style="max-width: 300px;"

      <p><strong>Estilo:</strong> {{ cerveza.estilo.nombre }}</p>
      <p><strong>Alcohol:</strong> {{ cerveza.porcentaje_alcohol }}%</p>
      <p><strong>IBU:</strong> {{ cerveza.ibu }}</p>
      <p><strong>Descripción:</strong> {{ cerveza.descripcion }}</p>

      <hr>
      <h4 class="mt-4">Barriles disponibles:</h4>
      <ul class="list-group list-group-flush">
        {% for barril in barriles %}
          <li class="list-group-item bg-secondary text-white">
            {{ barril.litros }}L - Precio estimado: ${{ barril.calcular_precio }}
            <br><img src="{{ barril.cerveza.foto.url }}" alt="{{ barril.cerveza.nombre }}" width="100" class="mt-2">
          </li>
        {% empty %}
          <li class="list-group-item bg-secondary text-white">No hay barriles disponibles.</li>
        {% endfor %}
      </ul>

      <div class="mt-4">
        <form action=""></form>
        <a href="{% url 'cerveza_update' cerveza.id %}" class="btn btn-warning">Editar</a>
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#confirmarEliminacionModal{{ cerveza.id }}">Eliminar</button>
        <a href="{% url 'cervezas' %}" class="btn btn-secondary">Volver al listado</a>

        <!-- Modal de confirmación -->
        <div class="modal fade" id="confirmarEliminacionModal{{ cerveza.id }}" tabindex="-1" aria-labelledby="modalLabel{{ cerveza.id }}" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="modalLabel{{ cerveza.id }}">Confirmar eliminación</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
              </div>
              <div class="modal-body text-dark">
                ¿Estás seguro que quieres eliminar la chopera {{ chopera.numero }}?
              </div>
              <div class="modal-footer">
                <form method="post" action="{% url 'cerveza_delete' cerveza.id %}">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-danger">Eliminar</button>
                </form>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
{% endblock %}

Catalogo/templates/cerveza_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
  <h2 style="color:white;">Editar Cerveza</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Guardar cambios</button>
    <a href="{% url 'cervezas' %}" class="btn btn-secondary">Cancelar</a>
  </form>
</div>
{% endblock %}

Catalogo/templates/cerveza_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
  <h1 class="text-center mb-5">Catálogo de Cervezas</h1>

  <div class="row g-4">
    {% for cerveza in cervezas %}
    <div class="col-12">
      <div class="card flex-row shadow-lg border-0 mt-4">
        {% if cerveza.foto %}
        <img src="{{ cerveza.foto.url }}" class="img-fluid" alt="{{ cerveza.nombre }}" style="width: 250px; object-fit: cover;">
        {% else %}
        <img src="{% static 'img/default-beer.jpg' %}" class="img-fluid" alt="Sin imagen" style="width: 250px; object-fit: cover;">
        {% endif %}

        <div class="card-body d-flex flex-column justify-content-between">
          <div>
            <h4 class="card-title text-primary">{{ cerveza.nombre }}</h4>
            <p class="card-text mb-1">
              <strong>Estilo:</strong> {{ cerveza.estilo.nombre }}<br>
              <strong>Alcohol:</strong> {{ cerveza.porcentaje_alcohol }}<br>
              <strong>IBU:</strong> {{ cerveza.ibu }}
            </p>
            <p class="text-muted">{{ cerveza.descripcion }}</p>
          </div>

          <a href="{% url 'servicios' cerveza.id %}" class="btn btn-outline-primary align-self-start">Pedir</a>
          {% if user.is_authenticated %}
          <a href="{% url 'cerveza' cerveza.id %}" class="btn btn-outline-primary align-self-start">Ver Detalle</a>
          {% endif %}

          {% with cerveza.barriles.all as barriles %}
          {% if barriles %}
          <div class="mt-3">
            <a><strong>Formatos disponibles:</strong></a>
            <div>
              {% for barril in barriles %}
              <div class="alert alert-light">
                <span style="color: black;">{{ barril.litros }}L - </span>
                <span class="text-success">Precio: ${{ barril.calcular_precio }}</span> 
              </div>
              {% endfor %}
            </div>
          </div>
          {% endif %}
          {% endwith %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% if user.is_authenticated %}
  <div class="text-center mt-5">
    <a class="btn btn-success btn-lg" href="{% url 'cerveza_new' %}">Agregar Cerveza</a>
    <a class="btn btn-primary" href="{% url 'grafico_ventas' %}">Grafico</a>
  </div>
  {% endif %}
</div>
{% endblock %}

Catalogo/templates/cerveza_new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container mt-5">
    <h2 style="color: white;" class="mb-4">Nueva Cerveza</h2>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-success">Guardar</button>
    </form>
  </div>
{% endblock %}

Catalogo/templates/editar_barril.html
{% extends "base.html" %}
{% block content %}
  <div class="container mt-5">
    <h2 style="color: white;">Editar Barril {{ barril.litros }}L</h2>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Guardar cambios</button>
    </form>
  </div>
{% endblock %}

Catalogo/templates/venta_form.html
{% extends 'base.html' %}
{% block content %}
{% if form.non_field_errors %}
  <div class="alert alert-danger">
    {{ form.non_field_errors }}
  </div>
{% endif %}

<div class="container mt-5">
    <h2 style="color: white;">Realizar Compra</h2>
    <p><strong>Cerveza:</strong> {{ cerveza.nombre }}</p>
    <p><strong>Servicio:</strong> {{ servicio.nombre }}</p>

    <form method="post">
        {% csrf_token %}
        {{ form.barril.label_tag }} {{ form.barril }}
        {{ form.cantidad.label_tag }} {{ form.cantidad }} <br>
        {{ form.fecha_alquiler.label_tag }} {{ form.fecha_alquiler }}

        <!-- Campos de ubicación -->
        <div class="form-group mt-3">
            <label for="id_provincia">Provincia:</label>
            <select name="provincia" id="id_provincia" class="form-control" required>
                <option value="">Seleccione una provincia</option>
                <option value="Salta">Salta</option>
                <!-- Agregá todas las provincias que necesites -->
            </select>
        </div>

        <div class="form-group mt-3">
            <label for="id_localidad">Localidad:</label>
            <input type="text" name="localidad" id="id_localidad" class="form-control" required>
        </div>

        <div class="form-group mt-3">
            <label for="id_direccion">Dirección exacta:</label>
            <input type="text" name="direccion" id="id_direccion" class="form-control" required>
        </div>

        <button type="submit" class="btn btn-primary mt-3">Confirmar Venta</button>
    </form>

    <a href="{% url 'servicios' cerveza.id %}" class="btn btn-secondary mt-3">Cancelar</a>
    <a href="{% url 'cervezas' %}" class="btn btn-secondary mt-3">Cancelar</a>

    <hr>
    <h4>Fechas disponibles este mes</h4>
    <div class="calendar-container table-responsive">
        <style>
            table {
                width: 100%;
                border-collapse: collapse;
            }
            th, td {
                border: 1px solid #ddd;
                padding: 8px;
                text-align: center;
            }
            .text-muted {
                color: #ccc;
            }
            .text-success {
                color: green;
            }
        </style>
        {{ calendario_html|safe }}
        <p><span class="text-success font-weight-bold">Números verdes:</span> días disponibles.</p>
        <p><span class="text-muted">Gris:</span> días ocupados.</p>
    </div>
</div>
{% endblock %}